title: #My first blog
author: Vab235
email: vab23.vb@gmail.com
description: 
This is a blog made by me on Github 

# social links
twitter_username: vab23_vb 
github_username:  Vab235  
show_excerpts: true
theme: minima
